// GENERATED by scripts/build-celebration-cinemas.js -- do not hand-edit.
// Celebration! Cinema locations, with coordinates from each page's own
// schema.org JSON-LD and the Vista cinema id from its dominant session prefix.
// Regenerate with: node scripts/build-celebration-cinemas.js --write
module.exports = [
  {
    "slug": "Celebration-Cinema-GR-North",
    "cinemaId": "002",
    "name": "Celebration Cinema GR North",
    "address": "2121 Celebration Dr. NE",
    "city": "Grand Rapids",
    "state": "MI",
    "lat": 43.0004,
    "lng": -85.5931
  },
  {
    "slug": "Celebration-Cinema-GR-South",
    "cinemaId": "004",
    "name": "Celebration Cinema GR South",
    "address": "1506 Eastport Drive SE",
    "city": "Grand Rapids",
    "state": "MI",
    "lat": 42.8494,
    "lng": -85.6304
  },
  {
    "slug": "Studio-Park",
    "cinemaId": "013",
    "name": "Celebration Cinema Studio Park",
    "address": "123 Ionia SW",
    "city": "Grand Rapids",
    "state": "MI",
    "lat": 42.9601,
    "lng": -85.6709
  },
  {
    "slug": "Celebration-Cinema-Rivertown",
    "cinemaId": "005",
    "name": "Celebration Cinema Rivertown",
    "address": "3728 Rivertown Pkwy",
    "city": "Grandville",
    "state": "MI",
    "lat": 42.8822,
    "lng": -85.7583
  },
  {
    "slug": "Celebration-Cinema-Lansing",
    "cinemaId": "006",
    "name": "Celebration Cinema Lansing",
    "address": "200 E. Edgewood Blvd",
    "city": "Lansing",
    "state": "MI",
    "lat": 42.6615,
    "lng": -84.5533
  },
  {
    "slug": "Studio-C-Meridian-Mall",
    "cinemaId": "012",
    "name": "Studio C! at Meridian Mall",
    "address": "1999 Central Park Drive",
    "city": "Okemos",
    "state": "MI",
    "lat": 42.7274,
    "lng": -84.4216
  },
  {
    "slug": "Celebration-Cinema-Crossroads",
    "cinemaId": "003",
    "name": "Celebration Cinema Crossroads",
    "address": "6600 Ring Road",
    "city": "Portage",
    "state": "MI",
    "lat": 42.221,
    "lng": -85.5981
  },
  {
    "slug": "Cinema-Carousel",
    "cinemaId": "009",
    "name": "Cinema Carousel",
    "address": "4289 Grand Haven Rd",
    "city": "Muskegon",
    "state": "MI",
    "lat": 43.1742,
    "lng": -86.2212
  },
  {
    "slug": "Celebration-Cinema-Benton",
    "cinemaId": "007",
    "name": "Celebration Cinema Benton Harbor",
    "address": "1468 Cinema Way",
    "city": "Benton Harbor",
    "state": "MI",
    "lat": 42.0764,
    "lng": -86.4227
  },
  {
    "slug": "Celebration-Cinema-Mt-Pleasant",
    "cinemaId": "008",
    "name": "Celebration Cinema Mt. Pleasant",
    "address": "4935 East Pickard Road",
    "city": "Mt. Pleasant",
    "state": "MI",
    "lat": 43.614,
    "lng": -84.7499
  },
  {
    "slug": "Getty-Drive-In",
    "cinemaId": "011",
    "name": "Getty Drive-In",
    "address": "920 E Summit Ave",
    "city": "Muskegon",
    "state": "MI",
    "lat": 43.1965,
    "lng": -86.2205
  }
];
